### PR TITLE
Update to 3.4.1

### PR DESCRIPTION
**Pull request by Maegorn**
I apply a patch to port the kernel to 3.4.1 version. No bugs or malfunctions in my opinion.

### CODE REVIEW

**Comment by xingrz** [comment]
@Maegorn Cool!

Since I'm not good at kernel, @BambooIV would you please review this PR?

**Comment by Maegorn** [comment]
Btw i'm testing every patch and i compared my modification with a 3.4.111 kernel from z7 (nx505j) and now everything works perfectly. Maybe we can create an other branch with updated kernel and let cm-13.0 clean.

**Comment by BambooIV** [comment]
Good idea

**Comment by xingrz** [comment]
@Maegorn In my option, the purpose of the `nx503a-dev` organization is to maintain a generic, working device configuration that can be easily port to popular Android projects for the device `nx503a`.

Take kernel for example. To keep the code base clear and maintainable, we want to keep the difference to CAF. In this way we are able to follow the further changes of CAF easily without having to solve too many conflicts.

That is, you are welcomed to build your variant ROMs based on the fork of our sources. But unless a change is necessary and reasonable, it won't be merged into this organization.

Anyway, thank you for your PR. Sorry for the unpleasant.

**Comment by Maegorn** [comment]
It's not unpleasant, i understood the question, so i'll pull only useful changes and not the one that may cause problems :+1:

**Pull request closed without merging**
